default:
  start_price: 1.20
  price_limit: 3
  price_band: 5
  tick_size: 0.001
  market_buy: 0.55
  market_sell: 0.5
  bid_order_ratio: 3
  ask_order_ratio: 3
  cancel_bid: 0.8
  cancel_ask: 0.8
  days: 10
  min_order_size: 250
  max_order_size: 5000
  order_step_size: 100

test:
  days: 1

production:
  days: 28
